print('Qual é a sua data de nascimento ?')
a1 = int(input('Dia:'))
a2 = str(input('Mês:'))
a3 = int(input('Ano:'))
print(type(a1))
print(type(a2))
print(type(a3))
print('Eu nasci dia {} de {} de {}.'.format(a1, a2, a3))
print(a2.isalpha())
print(a2.isnumeric())
print(a2.isupper())
print(a2.islower())
